### PR TITLE
Add support for PostgreSQL's LISTEN / NOTIFY

### PR DESCRIPTION
**Pull request by kaare**
A friendly pull request to add support for PQnotifies (the equivalent in Perl 5 DBD::Pg is called pg_notifies, so I do the same here).

There's a test, but there my be naming issues. I hope you'll consider this PR, as I need the functionality.

### CODE REVIEW

**Comment by abraxxa** [comment]
As Perl 6 supports the dash character in methodnames I'd suggest to name the method pg-notifies or define a prefix for database specific methods and use that.

**Comment by kaare** [comment]
I have no problem changing the name. I added tests for NOTIFY with payload as well

**Comment by salortiz** [comment]
A few comments:
+ An `is native` *method* should not declare its invocant as an *extra* argument, it is passed automatically; if you wish you can declare the need of the defined invocant as `PGconn:D:` (note the final colon)
+ In a `CStruct`, private members at the end should be omitted for safety.
+ It is documented that:  "After processing a PGnotify object returned by PQnotifies, be sure to free it with PQfreemem. It is sufficient to free the PGnotify pointer".

**Comment by Skarsnik** [comment]
Add an entry in the documentation for this :)

**Comment by kaare** [comment]
salortiz: I'd like to add an 'is export' to PQfreemem to be able to use it in DBDish::Pg::Connection. The logic belongs there. Is that OK? Also, I don't know how to free a CStruct when the sub expects a Pointer. 

I realize it's probably very basic Perl 6 stuff, but this is yak shaving for my Perl 6 learning project...

Skarsnik: You mean "Add documentation to DBDish::Pg::Connection"? ;-)

Or does the doc live in another place I didn't find yet?

**Comment by salortiz** [comment]
@kaare, The method `escapeBytea` is a good example of wrapping a native call that needs memory management, you don't need to do that in the upper level. 

I suggest you a similar approach: change the signature of `PQnotifies` to return `Pointer`, then use `nativecast` to get the `PGnotify`, copy the needed members to an uppper-level object  for return them, and use a LEAVE block to call `PQfreemem`. 

I could do that, but I would like you to try. :-)

**Comment by kaare** [comment]
OK, I've done it that way, as it seems to be BP here.

**Comment by Skarsnik** [comment]
I mean in the Readme. I don't think people read the (non existing?) pod on modules.

**Comment by kaare** [comment]
What do I know; I'm new around here :-)

**Comment by salortiz** [comment]
Done, thanks for the patience.

**Pull request merged**
