### PR TITLE
DBDish::Oracle, Test::DBDish and typed return value changes (Num -> Rat)

### PR DESCRIPTION
**Pull request by abraxxa**
Please review and comment what you like to have changed before it gets merged.
If we already want to keep the DBDish modules out of DBIish that's fine for me too, in which case I'd like to have the test and typed work to get merged.
As soon as this is completed I'll start working on DBIish and its API itself (see open issues on RaiseError for example).

### CODE REVIEW

**Comment by Skarsnik** [comment]
You forget to remove Data::Dump in the tests (or add it to the deps) so Travis can run success

**Comment by abraxxa** [comment]
I did add the dependency: https://github.com/perl6/DBIish/pull/49/files#diff-bcb1db43e3afbc2292948a804dfe435cR7
Is thy syntax wrong?

**Comment by jonathanstowe** [comment]
The problem is that the travis build is not doing "panda installdeps ." so it is not installing the Data::Dump, fix that and it'll be great :)

**Comment by zaucker** [comment]
Probably the PATH is not set for the script to find panda. Look at the log, it is probably mentioned there somewhere. This seems to be a problem for a few days now, I don't know what changed, it was not necessary before.

**Comment by abraxxa** [comment]
I guess panda isn't installed at all, just moar using rakudobrew.

**Comment by jonathanstowe** [comment]
I think that got fixed again, certainly I've seen things passing today with quite sizeable dependency chains :)

**Comment by abraxxa** [comment]
Yes, that seems to be the case: https://docs.travis-ci.com/user/languages/perl6/#Dependency-Management

**Comment by abraxxa** [comment]
I've rebased my DBIish pull-request, the Travis setup seems to work now (finds the dependent modules), the fails are the same as on my dev box and subject to API discussion

**Comment by jonathanstowe** [comment]
Can I make a suggestion as to merging this into a new branch within DBish then it will be easier for people to fix up, I'm quite happy to do this if every one else is agreeable.

**Comment by Skarsnik** [comment]
The failures are due to bad reference data (so error in the test) since
every fetch_ are expected to return Str and are tested against typed data,
returning something else is an API change yes.
A branch could be interesting to discuss this.

2016-02-07 12:47 GMT+01:00 Jonathan Stowe <notifications@github.com>:

> Can I make a suggestion as to merging this into a new branch within DBish
> then it will be easier for people to fix up, I'm quite happy to do this if
> every one else is agreeable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/perl6/DBIish/pull/49#issuecomment-180999906>.
>



-- 
Sylvain "Skarsnik" Colinet

Victory was near but the power of the ring couldn't be undone

**Comment by jonathanstowe** [comment]
Right I've pushed this into https://github.com/perl6/DBIish/tree/oracle I'd suggest fixing up the tests or simply cherry-picking the known working parts to get it working as soon as practical.

**Comment by jonathanstowe** [comment]
I've just fixed the t/35-pg-common.t so it skips if the environment variable isn't set. I could probably fix up the sqlite tests that are failing but I don't have any of the other DB stuff to test the rest.

**Comment by jonathanstowe** [comment]
By the way I've just bisected the branch and there are no commits worth cherry-picking, I'd suggest resolving the Rat thing that is causing the tests to fail and merging the lot.

**Comment by abraxxa** [comment]
What about the test suite refactoring into a module?

**Comment by jonathanstowe** [comment]
It looks good and I'd say it should go in but the tests would need to actually pass before it can be merged, the problem being the comparison of the return types, I'm not sure if this some subsequent change or something else.

**Comment by jonathanstowe** [comment]
BTW it is the cdeb80a57006d2163bc778129347a98e77a70a94 that broke those tests it seems.

**Comment by abraxxa** [comment]
Thanks for bisecting.
I've added those while working on the different data types to exactly see which one doesn't work.
I've set up SQLite, PostgreSQL and MariaDB so I can work on fixing it.

**Comment by jonathanstowe** [comment]
Cool, it wasn't immediately clear to me why tests _were_ failing to be honest as on the face of it the data actually looked right but it was testing it against the wrong things somehow.

**Comment by jonathanstowe** [comment]
I've been trying to keep the oracle branch in a mergeable state but there doesn't seem to be any movement on it apart from that

**Comment by jonathanstowe** [comment]
Still not quite good BTW as it gets:

```
P6M Merging GLOBAL symbols failed: duplicate definition of symbol DBDish
  in any merge_globals at gen/moar/m-ModuleLoader.nqp line 177
  in method install_driver at /home/jonathan/devel/perl6/DBIish/lib/DBIish.pm6 line 18
  in method run-tests at /home/jonathan/devel/perl6/DBIish/t/lib/Test/DBDish.pm6
```

**Comment by jonathanstowe** [comment]
right, It's looking in better shape now, however it appears that the MySQL type mappings differ from the pg and sqlite.  I'm going to open an issue for this as it's more likely to get fixed.

**Pull request merged**
