### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by fayland**

### CODE REVIEW

**Comment by zoffixznet** [comment]
Thanks.

**Comment by moritz** [comment]
FWIW it's not very useful to run the CI without supplying any databases to work against.

**Comment by szabgab** [comment]
One can ask Travis to install a database before running the tests: http://docs.travis-ci.com/user/database-setup/ by adding some extra lines to .travis.yml

**Comment by fayland** [comment]
make sense. I'll do more work and submit PR again. ty

**Pull request merged**
