### PR TITLE
Improve error message for lazy allrows data

### PR DESCRIPTION
**Pull request by rbt**
The data it returns is lazy and disappears on disposal of the database handle for some drivers. Throw an error message mentioning .eager can work around the issue.

Previous, this pattern:

	my $sth = $dbh.prepare($query);
	my $data = $sth.allrows(:array-of-hash);
	$dbh.dispose;
	for $data -> $row {}

Would return this type of error for Pg:
	No such method 'PQgetisnull' for invocant of type 'Any'
	  in code  at /home/rbt/work/DBIish/lib/DBDish/Pg/StatementHandle.pm6 (DBDish::Pg::StatementHandle) line 108
	  in method _row at /home/rbt/work/DBIish/lib/DBDish/Pg/StatementHandle.pm6 (DBDish::Pg::StatementHandle) line 102
	  in method row at /home/rbt/work/DBIish/lib/DBDish/StatementHandle.pm6 (DBDish::StatementHandle) line 81
	  in block  at /home/rbt/work/DBIish/lib/DBDish/StatementHandle.pm6 (DBDish::StatementHandle) line 97

### CODE REVIEW

**Comment by rbt** [comment]
Are there any thoughts on this fix? Another method is to pull in any unread data during dispose but that could be a ton of work for the common case where the code will immediately toss it.

**Comment by rbt** [comment]
@jonathanstowe I'm not certain I followed your statement.

Lazy, in this case, is from the DB Drivers memory allocations on the client side after receiving data from the server. Pg, and I believe all other currently supported DB client libraries, allocate a bucket of memory to hold the records and calling .dispose free's this storage.

allrows() being lazy relies on the driver allocated storage while accessing the data-structure it provides.

Automatic cursors (fetching from server on demand) is likely a problem too but it's also rare.


We could use a calldown to the driver to ask if the record set is available or have each driver implement the error check, but I think only a PureRaku driver would find that design useful.

**Comment by jonathanstowe** [comment]
No, my point was simpler than that,

It appears that you'd get the message if you did something like:

```
$sth.dispose;
....
my $row = $sth.row;
```

In which case the message would be confusing.

**Comment by rbt** [comment]
Ahh, yes. That's not ideal.

I updated the patch with separate error messages for the 3 different problem functions. I did not touch the undocumented legacy functions.

**Pull request merged**
